apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bakehouse
  name: bakehouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bakehouse
  template:
    metadata:
      labels:
        app: bakehouse
    spec:
      containers:
      - name: bakehouse
        image: husseinghoraba/bakehouse:${BUILD_NUMBER}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources: {}
